-- Import invite data from INVITE_LIST.ts
-- Run this after creating the tables with create_invites_tables.sql
-- This script uses UUIDs generated by the database

-- Party 1: Smith (John & Jane)
-- Note: Using gen_random_uuid() for IDs, but you can replace with specific UUIDs if needed
DO $$
DECLARE
  party1_id UUID;
  party2_id UUID;
  party3_id UUID;
  party4_id UUID;
BEGIN
  -- Party 1: Smith (John & Jane)
  INSERT INTO parties (last_name) VALUES ('Smith') RETURNING id INTO party1_id;
  INSERT INTO party_members (party_id, first_name, last_name) VALUES
    (party1_id, 'John', 'Smith'),
    (party1_id, 'Jane', 'Smith');

  -- Party 2: Johnson (Bob)
  INSERT INTO parties (last_name) VALUES ('Johnson') RETURNING id INTO party2_id;
  INSERT INTO party_members (party_id, first_name, last_name) VALUES
    (party2_id, 'Bob', 'Johnson');

  -- Party 3: Doe (John & Jane)
  INSERT INTO parties (last_name) VALUES ('Doe') RETURNING id INTO party3_id;
  INSERT INTO party_members (party_id, first_name, last_name) VALUES
    (party3_id, 'John', 'Doe'),
    (party3_id, 'Jane', 'Doe');

  -- Party 4: Smith (Jake & Jamie) - Different Smith family
  INSERT INTO parties (last_name) VALUES ('Smith') RETURNING id INTO party4_id;
  INSERT INTO party_members (party_id, first_name, last_name) VALUES
    (party4_id, 'Jake', 'Smith'),
    (party4_id, 'Jamie', 'Smith');
END $$;

